name: flutter_network_connectivity
description: A Flutter Plugin to check for live network connectivity status. Plugin uses NetworkCapabilities for
  Android and NetworkMonitor for iOS.
version: 0.0.5
homepage: https://github.com/praveen-gm/flutter_network_connectivity

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  lints: ^1.0.1
  flutter_lints: ^1.0.4

flutter:
  plugin:
    platforms:
      android:
        package: com.livelifedev.flutter_network_connectivity
        pluginClass: FlutterNetworkConnectivityPlugin
      ios:
        pluginClass: FlutterNetworkConnectivityPlugin